"""Mesh the showcase model into Wavefront ``.obj`` files for visual inspection in Blender.

This is a **validation harness**, not the production 3D pipeline — the real output layer is
``roadup/usd`` (Phase 5), which emits id-tagged USD. Here we reuse the already-built sampler
(:class:`roadup.opendrive.eval.sampler.Sampler`) and mesher
(:class:`roadup.geometry.mesh.MeshBuilder`) to turn each showcase road into ribbons so the topology
(reference-line shape, lane widths/tapers, continuity across links) can be eyeballed.

Run from the repo root (venv active)::

    python examples/generate_obj_meshes.py

Writes into ``examples/out/`` (gitignored), beside the ``.xodr`` files:

* ``showcase.obj``       — all roads in one file (matches ``showcase.xodr``).
* ``NN_<name>.obj``      — each road on its own.

Each road becomes several **separate objects** so they are individually selectable in Blender:
``<road>_Surface`` (the drivable ribbon) and one ``<road>_Lane_<id>`` per lane.

**Axis convention — meters, Z-up**, matching the ``.xodr`` truth and the (Phase 5) USD stage
(``upAxis="Z"``). OBJ cannot *declare* an up-axis, so use a viewer that lets you set it: in Blender,
import with *Up: Z, Forward: Y*. Generic **Y-up** viewers (e.g. VSCode's built-in mesh preview) will
render the network tilted 90° — that's the viewer's assumption, not a coordinate error here.

The road surface is dropped 2 cm so the per-lane ribbons render cleanly above it (legibility only).
"""
from __future__ import annotations

import re
from pathlib import Path

from examples.showcase import build_showcase_model, showcase_roads
from roadup.common.types import Vec3
from roadup.geometry.mesh import MeshBuilder, MeshData
from roadup.intersections.surface import IntersectionSurface
from roadup.opendrive.eval.sampler import Sampler
from roadup.opendrive.model.network import OpenDriveModel

OUT_DIR = Path(__file__).parent / "out"
_SURFACE_DROP = 0.02  # metres the surface sits below the lane ribbons (avoid z-fighting)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")


def _drop_z(points: list[Vec3], dz: float) -> list[Vec3]:
    return [(x, y, z - dz) for (x, y, z) in points]


def road_meshes(sampler: Sampler, road_id: str) -> list[tuple[str, MeshData]]:
    """Build the (name, mesh) ribbons for one road: a surface ribbon + one ribbon per lane."""
    builder = MeshBuilder()
    frames = sampler.reference_frames(road_id)
    meshes: list[tuple[str, MeshData]] = []
    if len(frames) < 2:
        return meshes

    left, right = sampler.road_surface_polylines(road_id)
    if len(left) >= 2 and len(right) >= 2:
        surface = builder.ribbon(_drop_z(left, _SURFACE_DROP), _drop_z(right, _SURFACE_DROP))
        meshes.append((f"{road_id}_Surface", surface))

    for lb in sampler.lane_boundaries(road_id, frames[0].s, frames[-1].s):
        if len(lb.inner) >= 2 and len(lb.outer) >= 2:
            meshes.append((f"{road_id}_Lane_{lb.lane_id}", builder.ribbon(lb.inner, lb.outer)))
    return meshes


def model_meshes(model: OpenDriveModel, step: float = 1.0) -> list[tuple[str, MeshData]]:
    """All (name, mesh) ribbons for the model: each non-junction road, plus one junction surface.

    Connecting roads (``road.junction is not None``) are omitted as individual ribbons because the
    junction surface already unions them (see ``roadup.intersections.surface.IntersectionSurface``).
    """
    sampler = Sampler(model, step=step)
    meshes: list[tuple[str, MeshData]] = []
    for road_id, road in model.roads.items():
        if road.junction is not None:
            continue
        meshes.extend(road_meshes(sampler, road_id))
    for junction_id, junction in model.junctions.items():
        surface = IntersectionSurface(sampler).generate(junction)
        if surface.points:
            meshes.append((f"{junction_id}_Surface", surface))
    return meshes


def write_obj(path: Path, named_meshes: list[tuple[str, MeshData]]) -> int:
    """Write named meshes to one ``.obj`` (each entry a separate object). Returns the face count."""
    lines: list[str] = ["# Generated by examples/generate_obj_meshes.py — meters, Z-up"]
    v_base = 0
    faces = 0
    for name, mesh in named_meshes:
        lines.append(f"o {name}")
        for x, y, z in mesh.points:
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        cursor = 0
        for count in mesh.face_vertex_counts:
            verts = mesh.face_vertex_indices[cursor:cursor + count]
            cursor += count
            lines.append("f " + " ".join(str(v_base + v + 1) for v in verts))  # OBJ is 1-indexed
            faces += 1
        v_base += len(mesh.points)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return faces


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    combined = build_showcase_model()
    combined_path = OUT_DIR / "showcase.obj"
    faces = write_obj(combined_path, model_meshes(combined))
    print(f"wrote {combined_path}  ({len(combined.roads)} roads, {faces} faces)")

    for i, road in enumerate(showcase_roads(), start=1):
        single = OpenDriveModel()
        single.add_road(road)
        note = road.user_data.get("note", road.id)
        path = OUT_DIR / f"{i:02d}_{_slug(note)}.obj"
        faces = write_obj(path, model_meshes(single))
        print(f"wrote {path}  ({note}, {faces} faces)")


if __name__ == "__main__":
    main()
